<?php

declare(strict_types=1);

namespace App\Middleware;

use App\Auth\Roles;
use App\Exception\AuthException;
use App\Service\TokenService;
use App\Support\RequestContext;
use App\Tenancy\TenantContext;
use Illuminate\Database\Capsule\Manager as Capsule;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Slim\Psr7\Response;

/**
 * Establishes who is calling, and therefore which organisation's data they see.
 *
 * This is the only place a tenant is set for a request. Everything downstream
 * reads it through the model scope, so a route that skips this middleware
 * cannot quietly read across organisations — the scope throws instead. That is
 * why TenantContext fails closed rather than defaulting to unfiltered.
 *
 * THE TOKEN SAYS WHO, THE DATABASE SAYS WHAT THEY MAY DO. A signed token is
 * proof of identity and nothing else here: the role, whether the account is
 * still switched on, and whether its password is still a shared secret are all
 * read live, on every request.
 *
 * Trusting the claims instead made every access token a licence that outlived
 * the decision to withdraw it, for the quarter of an hour until it expired.
 * A demoted administrator could spend that window putting themselves back —
 * these routes trusted the role in the token, so the demotion had no effect at
 * all. A deactivated account kept working. A password reset, which exists
 * precisely to take an account away from whoever has its password, left the
 * session it was called to end running.
 *
 * The cost is two indexed lookups per authenticated request: the account, and
 * what its role may do. That is the whole price of "revoked means revoked", and
 * the alternative — a shorter token life — only narrows the window rather than
 * closing it.
 */
final class AuthMiddleware implements MiddlewareInterface
{
    /**
     * @param bool $requireUsablePassword false only on the route that exists to
     *                                    fix an unusable one. Passed explicitly
     *                                    rather than matched against the path,
     *                                    so the exemption is visible where the
     *                                    routes are declared and cannot be
     *                                    widened by choosing a URL.
     */
    public function __construct(
        private readonly TokenService $tokens = new TokenService(),
        private readonly bool $requireUsablePassword = true,
    ) {
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $header = $request->getHeaderLine('Authorization');

        if (!preg_match('/^Bearer\s+(\S+)$/i', $header, $matches)) {
            return $this->unauthorized('A bearer token is required.');
        }

        $claims = $this->tokens->verify($matches[1]);

        if ($claims === null) {
            return $this->unauthorized('The token is not valid. Sign in again.');
        }

        // Read unscoped — the tenant is not established until below, and this
        // is what establishes it. The organisation from the token is part of
        // the lookup rather than trusted from it, so a token naming an
        // organisation the account does not belong to matches nothing.
        $account = Capsule::table('users')
            ->join('roles', 'roles.id', '=', 'users.role_id')
            ->join('organizations', 'organizations.id', '=', 'users.organization_id')
            ->where('users.id', $claims['sub'])
            ->where('users.organization_id', $claims['org'])
            ->first([
                'users.is_active',
                'users.must_change_password',
                'roles.id as role_id',
                'roles.key as role',
                'organizations.programme_id',
                'organizations.is_active as organization_active',
            ]);

        // Deleted, deactivated, or belonging to an organisation that has been
        // switched off. 401 rather than 403: the credential is no longer good,
        // and the client should go and get another rather than assume this
        // particular route is closed to it.
        if ($account === null || !$account->is_active || !$account->organization_active) {
            return $this->unauthorized('This account is no longer active. Sign in again.');
        }

        $role = (string) $account->role;

        // A password handed over by an administrator, or generated by
        // bin/recover-access and read out over a phone, is a shared secret
        // until it is changed. Until then the account does nothing else — and
        // taken from the row rather than the token, so a reset issued a moment
        // ago binds the session that was already open.
        if ($this->requireUsablePassword && (bool) $account->must_change_password) {
            return $this->forbidden(AuthException::passwordChangeRequired()->getMessage());
        }

        // Also on a static, because the request logger runs outside routing
        // and a PSR-7 attribute set here is invisible to anything wrapping
        // this. See RequestContext.
        RequestContext::setSessionHash($claims['sid']);

        TenantContext::set(
            $claims['org'],
            $claims['sub'],
            in_array($role, ['admin', 'superadmin'], true),
            $account->programme_id === null ? null : (int) $account->programme_id,
        );

        return $handler->handle(
            $request
                ->withAttribute('user_id', $claims['sub'])
                ->withAttribute('organization_id', $claims['org'])
                ->withAttribute('role', $role)
                // What the account may do, read from the role's rows rather
                // than inferred from its name. Resolved here so it is read
                // once, on the same doctrine as everything above: a
                // capability withdrawn is withdrawn on the next request, not
                // when the token runs out.
                ->withAttribute('permissions', Roles::permissionsOf((int) $account->role_id))
                // Read by the request log and the audit trail. Put here
                // because this is the only place that has verified the token
                // it came from — anything downstream reading it from a header
                // would be reading something the caller chose.
                ->withAttribute('session_hash', $claims['sid'] ?? null),
        );
    }

    private function unauthorized(string $message): ResponseInterface
    {
        return $this->error(401, $message);
    }

    /**
     * Carries a machine-readable code as well as prose.
     *
     * The client has to route to the change-password screen on this, and
     * matching on an English sentence would break the moment the sentence is
     * translated or reworded.
     */
    private function forbidden(string $message): ResponseInterface
    {
        return $this->error(403, $message, 'password_change_required');
    }

    private function error(int $status, string $message, ?string $code = null): ResponseInterface
    {
        $body = ['status' => $status, 'message' => $message];

        if ($code !== null) {
            $body['code'] = $code;
        }

        $response = new Response($status);
        $response->getBody()->write((string) json_encode(['error' => $body]));

        return $response->withHeader('Content-Type', 'application/json');
    }
}
