<?php

declare(strict_types=1);

namespace App\Middleware;

use App\Exception\AuthException;
use App\Service\TokenService;
use App\Tenancy\TenantContext;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Slim\Psr7\Response;

/**
 * Establishes who is calling, and therefore which organisation's data they see.
 *
 * This is the only place a tenant is set for a request. Everything downstream
 * reads it through the model scope, so a route that skips this middleware
 * cannot quietly read across organisations — the scope throws instead. That is
 * why TenantContext fails closed rather than defaulting to unfiltered.
 */
final class AuthMiddleware implements MiddlewareInterface
{
    /**
     * @param bool $requireUsablePassword false only on the route that exists to
     *                                    fix an unusable one. Passed explicitly
     *                                    rather than matched against the path,
     *                                    so the exemption is visible where the
     *                                    routes are declared and cannot be
     *                                    widened by choosing a URL.
     */
    public function __construct(
        private readonly TokenService $tokens = new TokenService(),
        private readonly bool $requireUsablePassword = true,
    ) {
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $header = $request->getHeaderLine('Authorization');

        if (!preg_match('/^Bearer\s+(\S+)$/i', $header, $matches)) {
            return $this->unauthorized('A bearer token is required.');
        }

        $claims = $this->tokens->verify($matches[1]);

        if ($claims === null) {
            return $this->unauthorized('The token is not valid. Sign in again.');
        }

        // A password handed over by an administrator, or generated by
        // bin/recover-access and read out over a phone, is a shared secret
        // until it is changed. Until then the account does nothing else.
        if ($this->requireUsablePassword && $claims['pwd']) {
            return $this->forbidden(AuthException::passwordChangeRequired()->getMessage());
        }

        TenantContext::set($claims['org'], $claims['sub'], $claims['admin']);

        return $handler->handle(
            $request
                ->withAttribute('user_id', $claims['sub'])
                ->withAttribute('organization_id', $claims['org'])
                ->withAttribute('role', $claims['role']),
        );
    }

    private function unauthorized(string $message): ResponseInterface
    {
        return $this->error(401, $message);
    }

    /**
     * Carries a machine-readable code as well as prose.
     *
     * The client has to route to the change-password screen on this, and
     * matching on an English sentence would break the moment the sentence is
     * translated or reworded.
     */
    private function forbidden(string $message): ResponseInterface
    {
        return $this->error(403, $message, 'password_change_required');
    }

    private function error(int $status, string $message, ?string $code = null): ResponseInterface
    {
        $body = ['status' => $status, 'message' => $message];

        if ($code !== null) {
            $body['code'] = $code;
        }

        $response = new Response($status);
        $response->getBody()->write((string) json_encode(['error' => $body]));

        return $response->withHeader('Content-Type', 'application/json');
    }
}
